name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


jobs:
  tests:
    name: Flow CLI Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: "true"
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20
    - name: Install Flow CLI
      run: bash -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)" -- v1.12.0-cadence-v1.0.0-M8-2
    - name: Run tests
      run: flow test --cover --covercode="contracts" --coverprofile="coverage.lcov" tests/test_*.cdc
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
